### ISSUE TITLE
Unable to use custom classifier (lizard + finetuned on new data)

### ISSUE THREAD

**Issue by e-candeloro** [TIO-IKIM/CellViT-plus-plus#11]
Hi, 

I'm opening this issue because I'm experiencing problems using a custom classifier in the inference pipeline.

If I use a custom classifier, like the lizard.pth you included in the repository, I experienced the following error during the cell extraction process:

`Traceback (most recent call last):
  File "/work/grana_urologia/MONKEY_challenge/source/sota_architectures/CellViT-plus-plus/./cellvit/detect_cells.py", line 100, in <module>
    main()
  File "/work/grana_urologia/MONKEY_challenge/source/sota_architectures/CellViT-plus-plus/./cellvit/detect_cells.py", line 44, in main
    celldetector.process_wsi(
  File "/work/grana_urologia/MONKEY_challenge/source/sota_architectures/CellViT-plus-plus/cellvit/inference/inference_memory.py", line 173, in process_wsi
    inference_results = [ray.get(call_id) for call_id in call_ids]
  File "/work/grana_urologia/MONKEY_challenge/source/sota_architectures/CellViT-plus-plus/cellvit/inference/inference_memory.py", line 173, in <listcomp>
    inference_results = [ray.get(call_id) for call_id in call_ids]
  File "/work/grana_urologia/MONKEY_challenge/source/sota_architectures/CellViT-plus-plus/cellvit_env/lib/python3.10/site-packages/ray/_private/auto_init_hook.py", line 22, in auto_init_wrapper
    return fn(*args, **kwargs)
  File "/work/grana_urologia/MONKEY_challenge/source/sota_architectures/CellViT-plus-plus/cellvit_env/lib/python3.10/site-packages/ray/_private/client_mode_hook.py", line 103, in wrapper
    return func(*args, **kwargs)
  File "/work/grana_urologia/MONKEY_challenge/source/sota_architectures/CellViT-plus-plus/cellvit_env/lib/python3.10/site-packages/ray/_private/worker.py", line 2624, in get
    raise value.as_instanceof_cause()
ray.exceptions.RayTaskError(RuntimeError): ray::BatchPoolingActor.convert_batch_to_graph_nodes() (pid=4123229, ip=155.185.49.161, actor_id=8d6343ee307ece6b34769cda01000000, repr=<cellvit.inference.postprocessing_cupy.BatchPoolingActor object at 0x14c04122b1c0>)
  File "/work/grana_urologia/MONKEY_challenge/source/sota_architectures/CellViT-plus-plus/cellvit/inference/postprocessing_cupy.py", line 666, in convert_batch_to_graph_nodes
    batch_cell_tokens_pt = torch.stack(batch_cell_tokens)
RuntimeError: stack expects a non-empty TensorList`

This case only arises when I use a custom classifier with few classes, like the lizard or a custom one I fine-tuned using your instructions. It works when evaluated with 5-fold cross-validation on the 5 validation tests.

It seems there is a problem when only a few classes are employed for the custom classifier and no cells in the 1024x1024 patches are found.

To give some context, I'm working with a PAS WSI for kidneys that present a lot of background and have few pieces of tissue.

![Image](https://github.com/user-attachments/assets/3dffb490-5913-433a-a357-e97cc65c4cf8)

**Comment by e-candeloro** [comment]
Hi, I'm also experiencing another issue: when i use the flag --binary and provide a filelist of .tif WSIs with a fixed mpp and zoom level, after one/two processed images I get this error:

`Traceback (most recent call last):
  File "/work/grana_urologia/MONKEY_challenge/source/sota_architectures/CellViT-plus-plus/./cellvit/detect_cells.py", line 100, in <module>
    main()
  File "/work/grana_urologia/MONKEY_challenge/source/sota_architectures/CellViT-plus-plus/./cellvit/detect_cells.py", line 65, in main
    celldetector.process_wsi(
  File "/work/grana_urologia/MONKEY_challenge/source/sota_architectures/CellViT-plus-plus/cellvit/inference/inference_memory.py", line 156, in process_wsi
    for batch_num, batch in enumerate(wsi_inference_dataloader):
  File "/work/grana_urologia/MONKEY_challenge/source/sota_architectures/CellViT-plus-plus/cellvit_env/lib/python3.10/site-packages/pathopatch/patch_extraction/dataset.py", line 760, in __next__
    patches = torch.tensor(patches[0][None, ...])
IndexError: list index out of range`

**Comment by OliS1311** [comment]
I've had this issue with custom classifiers:

`RuntimeError: stack expects a non-empty TensorList`

It doesn't seem to happen if I run `process_dataset` rather than `process_wsi`, have you tried that?

**Comment by e-candeloro** [comment]
Hi, i didn't tried that, thanks!
Howevew I fixed my problem by predicting on an already patched dataset and using the test eval code for the classifier head finetuning.

**Comment by gitbirthdaycake** [comment]
I've just encountered this problem when running with process_dataset so presumably it's still an issue
